# TidyBot2 Left Arm Operating Modes

groups:
  left_arm:
    operating_mode: position
    profile_type: velocity
    profile_velocity: 131
    profile_acceleration: 25
    torque_enable: true

singles:
  left_gripper:
    operating_mode: pwm
    torque_enable: true
